class Protocol:
    STATUS_OK = "OK"
    STATUS_ERROR = "ERROR"
    
    # Auth
    CMD_REGISTER = "REGISTER"
    CMD_LOGIN_DEV = "LOGIN_DEV"
    CMD_LOGIN_PLAYER = "LOGIN_PLAYER"
    
    # Store (Developer)
    CMD_UPLOAD_GAME = "UPLOAD_GAME" # D1
    CMD_UPDATE_GAME = "UPDATE_GAME" # D2 
    CMD_LIST_MY_GAMES = "LIST_MY_GAMES" 
    CMD_UNPUBLISH_GAME = "UNPUBLISH_GAME" # D3
    
    # Store (Player)
    CMD_LIST_GAMES = "LIST_GAMES" # U1
    CMD_DOWNLOAD_GAME = "DOWNLOAD_GAME" # U2
    CMD_REVIEW_GAME = "REVIEW_GAME" # U4
    CMD_GET_REVIEWS = "GET_REVIEWS" # U4

    # U3
    CMD_CREATE_ROOM = "CREATE_ROOM"
    CMD_LIST_ROOMS = "LIST_ROOMS"
    CMD_JOIN_ROOM = "JOIN_ROOM"
    CMD_LEAVE_ROOM = "LEAVE_ROOM" 